# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI (Build and Test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install backend dependencies
    - name: Install backend dependencies
      run: npm ci

    # Install frontend dependencies
    - name: Install frontend dependencies
      run: npm ci --prefix ./client

    # Install Playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Build
    - name: Build
      run: npm run build --if-present

    # Frontend Test
    - name: Run frontend unit and integration tests
      run: npm run test:frontend -- --coverage

    # Backend Test
    - name: Run backend unit and integration tests
      run: npm run test:backend -- --coverage

    # UI Test
    - name: Run UI tests 
      run: npm run test:ui
      env:
        DEV_MODE: test
